POST http://localhost:3000/addcampingcategory.test.php
Content-Type: application/x-www-form-urlencoded

CampingCategoryID=6
&CampingCategoryCode=TEST
&CampingCategoryName=This is created only for submission
&DateCreated=NOW()
&aisleNumber=6

###//Anusha Patel, March 14 2025, IT202 Section 006, Phase 2, ap3235@njit.edu

GET http://localhost:3000/listcampingcategory.test.php

###
POST http://localhost:3000/changecategory.test.php
Content-Type: application/x-www-form-urlencoded

CampingCategoryID=6
&CampingCategoryCode=TESTY
&CampingCategoryName= TEST ONLY
&DateCreated=NOW()
&aisleNumber=6

###
###
POST http://localhost:3000/removecampingcategory.test.php
Content-Type: application/x-www-form-urlencoded

CampingCategoryID=6