POST http://localhost:3000/addCampingProducts.test.php
Content-Type: application/x-www-form-urlencoded


CampingProductID=5
&CampingProductName="TEST"
&CampingCategoryID=15
&CampingListPrice=10.0
###
GET http://localhost:3000/listcampingproducts.test.php
POST http://localhost:3000/changeitem.test.php
Content-Type: application/x-www-form-urlencoded


CampingProductID=5
&CampingProductName="TEST"
&CampingCategoryID=15
&CampingListPrice=10.0
###
POST http://localhost:3000/removecampingproduct.test.php
Content-Type: application/x-www-form-urlencoded


itemID=5
