POST http://localhost:3000/addcampingcategory.test.php
Content-Type: application/x-www-form-urlencoded

CampingCategoryID=2
&CampingCategoryCode="dfks"
&CampingCategoryName="ppp"
&DateCreated=NOW()
&aisleNumber=5




###
GET http://localhost:3000/listcampingcategory.test.php
###
POST http://localhost:3000/changecategory.test.php
Content-Type: application/x-www-form-urlencoded

CampingCategoryID=3
&CampingCategoryCode="dfks"
&CampingCategoryName="ppp"
&DateCreated=NOW()
&aisleNumber=7


